### ISSUE TITLE
hosted putsreq down?

### ISSUE THREAD

**Issue by ddavtian** [phstc/putsreq#44]
Seems to go down quite a few times a day, anyway to mitigate the issue? Many thanks again for a such a great service.

:pushpin: #45

**Comment by phstc** [comment]
Hi @ddavtian 

I'm sorry for that, it is very annoying. I've reduced again from 60 requests per minute to 30, and blocked some IPs. It gets down because people abuse.

It should be working now.

**Comment by ddavtian** [comment]
thank you @phstc for your quick response. For me it's still not loading, hoping I am not one of those blocked IPs :-) I am not abusing it by any means

**Comment by ddavtian** [comment]
Just came up, Heroku was probably warming up the engines. Closing it, thank you again.

**Comment by ddavtian** [comment]
Seems to have gone down again :-(

**Comment by phstc** [comment]
@ddavtian I think I managed to fix the throttle. It should be up and running now for good 🙏
